name: Build APK

on:
  push:
  workflow_dispatch:
    inputs:
      XRAY_CORE_VERSION:
        description: 'Xray core version or commit hash'
        required: true
        default: 'latest'  # Optional: Set a default version

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH || echo "GOPATH is not set"

    - name: Setup Android environment
      uses: android-actions/setup-android@v3
      with:
        api-level: '30'  # Specify your required API level
        build-tools: '30.0.3'  # Specify your required build tools version
        ndk-version: '21.4.7075529'  # Specify a compatible NDK version

    - name: Build dependencies
      run: |
        mkdir -p ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        git clone --depth=1 -b main https://github.com/2dust/AndroidLibXrayLite.git
        cd AndroidLibXrayLite
        go get github.com/xtls/xray-core@${{ github.event.inputs.XRAY_CORE_VERSION }} || true
        gomobile init
        go mod tidy -v
        gomobile bind -v -androidapi 21 -ldflags='-s -w' ./  # Changed API level to 21

    - name: Copy AAR files from local directory
      run: |
        # Ensure the target libs directory exists
        mkdir -p ${{ github.workspace }}/V2rayNG/app/libs/
        
        # Copy AAR files from the local directory to the target directory
        cp /libs/*.aar ${{ github.workspace }}/V2rayNG/app/libs/

    - name: Build APK
      run: |
        cd ${{ github.workspace }}/V2rayNG
        ls -la  # List contents of the V2rayNG directory for debugging
        chmod 755 gradlew
        ./gradlew assembleDebug || exit 1

    - name: List APK output directory
      run: ls -la ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/debug/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/debug/
